### ISSUE TITLE
Bib Tex entry type having {,} this or {"} not formatted correctly

### ISSUE THREAD

**Issue by coolguy97** [MaikelH/BibtexLibrary#1]
I had an article as below .

@Article{ChgfgA,
author ="Author 1, Author 2",
title ="this text should be in double quotes {"}bio-tech{"} ",
journal ="ABC Journal.",
year ="2014",
volume ="5",
issue ="23",
pages ="46-49",
publisher ="The American Publisher",
doi ="",
url ="",
abstract ="This abstract has comma{,} and double quotes syntax {"}bio-tech{"} how can this be fixed"}

This a valid format but the parser gives error.

For first double quotes it's only single { is shown as output:
this text should be in double quotes {
For abstract Comma it throws in BibtexParser.cs
ParseException("Expected type Comma but found: " + token.GetType());

**Comment by MaikelH** [comment]
Ok this should work indeed. I wil have a look at it. Probably need to update the parser and grammar for  this to work.

I think there are more problems like this, because there is no official grammar for the bibtex.

**Comment by MaikelH** [comment]
The value quotes should work in version 1.1.

**Comment by MaikelH** [comment]
The fix for this bug will be included in the upcoming 1.2.0 release, that will be released within a few days.

**Comment by MaikelH** [comment]
This is fixed in the 1.2 release that is now on nuget.
