### ISSUE TITLE
Comments are not processed

### ISSUE THREAD

**Issue by fhaag** [MaikelH/BibtexLibrary#2]
The parser appears to choke on comment lines (starting with `%`). Like this, it is impossible to, for instance, directly load files written by the standard tool [JabRef](http://jabref.sourceforge.net/), which always puts the file encoding and a remark about how the file was generated as comments into the first lines of the `.bib` files.

**Comment by MaikelH** [comment]
Ah, yeah the comments should be discarded when parsing the file. Thanks for reporting the issue, I have some time the coming days so I will look into it.
